openapi: 3.0.0
info:
  title: "API Title"
  description: "API Description"
  version: "1.0.0"
paths:
  /api-blog/getAll:
    get:
      summary: "Example endpoint"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
components:
  schemas:
    Blog:
      type: object
      required:
        - title
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        image-url:
          type: string
